### ISSUE TITLE
Expand selection to tag doesn't work

### ISSUE THREAD

**Issue by Jeloi** [daaain/Handlebars#47]
Expanding selection to tag doesn't work when I set the syntax to be a Handlebars template.

The specific command is:
command: expand_selection {"to": "tag"}

which i have bound to cmd+shift+a.

**Comment by msantoro12** [comment]
Just thought I would let you know I am having this truly annoying problem as well. I was looking into it a bit, but since I have never written a language definition before, have only been able to do comparisons with other packages that work properly. 

I have been using the [Package​Resource​Viewer](https://packagecontrol.io/packages/PackageResourceViewer) to view a number of other included language packages that are functioning as expected. I have looked at the HTML(Rails) definition and think maybe you should look into that approach as well as a stand alone Handlebars definition.

**Comment by daaain** [comment]
Hey @msantoro12, I had a look, this PackageResoureViewer is basically just a shortcut to open files in installed packages as far as I can see.

I don't have HTML(Rails) language definition, which package does it come from?

**Comment by msantoro12** [comment]
Yes it is an easy way to view compressed packages in sublime quickly. Truthfully I think any HTML(LANG) would be a good example seeing as they are extending the existing HTML language syntax and handling.

**Comment by daaain** [comment]
I've added the Emmet package workaround to the README (thanks @designorant). Closing the issue as it's very unlikely that I'll ever get around to work on this given that there's a solution (and this issue is referenced from the README now), but of course PRs are still welcome.
