### ISSUE TITLE
Add syntax definitions for properties

### ISSUE THREAD

**Issue by sotojuan** [daaain/Handlebars#81]
Color schemes and themes can't make them easier to see because apparently there's no definitions for them.

[Example](https://github.com/saadq/Materialize/issues/61#issuecomment-217679799).

/cc @saadq

**Comment by daaain** [comment]
Hey @sotojuan,

I'm really sorry for taking this long, I briefly looked into it a few times, but struggling to understand what exactly is the problem or how can I help. Please try to describe what you're experiencing a bit better!

The (hash) helpers are defined as `meta.function.block.start.handlebars` and `support.constant.handlebars`, while properties are `meta.function.inline.other.handlebars` and `variable.parameter.handlebars`.

If you look at the example file in this repo, you should definitely see a distinction between them:
<img width="557" alt="screen shot 2016-05-28 at 21 27 06" src="https://cloud.githubusercontent.com/assets/69962/15629530/057ab64c-251b-11e6-8a04-f39c3fab023c.png">

**Comment by sotojuan** [comment]
Hi, thanks for the reply. I'll admit that I don't know anything about Sublime plugins or coloring, so maybe @saadq can help!

**Comment by saadq** [comment]
Hey @daaain, thanks for taking a look at this. I'm not too familiar with Handlebars, but I believe the issue was about this code snippet:

```handlebars

{{#x-card
  onsubmit=attrs.onsubmit
  title='Login to Peepchat'
  buttonText='Login'}}
  <div class="row">
    {{x-input
      value=model.email
      errors=validations.attrs.model.email.messages
      classNames='col s12'
      type='email'
      label='Username'}}
  </div>
  <div class="row">
    {{x-input
      value=model.password
      errors=validations.attrs.model.password.messages
      classNames='col s12'
      type='password'
      label='Password'}}
  </div>
{{/x-card}}

```

In Sublime, it currently looks like this:

<img width="1392" alt="screen shot 2016-05-31 at 2 18 48 pm" src="https://cloud.githubusercontent.com/assets/5678694/15685630/9c225f52-273a-11e6-9665-4ebc25c8b9fa.png">

While in Atom, it looks like this:

<img width="732" alt="hbs" src="https://cloud.githubusercontent.com/assets/5678694/15685643/ab2628a8-273a-11e6-9de0-8da15f87ebeb.png">

For example. this line: `onsubmit=attrs.onsubmit`. Is it possible for `onsubmit=` and `attrs.onsubmit` to be different colors?

**Comment by daaain** [comment]
Ah ok, thanks a lot for the explanation @saadq, I got it now!

I split attributes up, so now there is `entity.other.attribute-name.handlebars` and `entity.other.attribute-value.handlebars` which you should be able to target with themes.

But it's improved even without theme support as the equal sign should be a distinct colour:

![image](https://cloud.githubusercontent.com/assets/69962/15799822/9754592e-2a61-11e6-96cd-d279d7994fce.png)

**Comment by saadq** [comment]
Awesome, thanks a lot.

**Comment by daaain** [comment]
I'm closing this issue, but feel free to get back to me @saadq if there's anything else I should do!
