### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by timdiacon** [daaain/Handlebars#83]
Getting this error every time I open up an hbs file. Tried removing and reinstalling package but still throwing error?

`Error loading syntax file "Packages/Handlebars/grammars/Handlebars.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by daaain** [comment]
Hey @timdiacon,

What OS and editor, and which versions are you using?

Also, does it happen with any Handlebars file or just particular ones?

I just had a look and didn't get anything like this with Atom 1.7.4 or ST3 3114 on OS X 10.11.5.

**Comment by timdiacon** [comment]
I'm using the latest version of Sublime 4 on OSX 10.11.2

I'm getting it with all HBS files :-(

**Comment by daaain** [comment]
Sublime 4? Am I behind the times or is that a typo? :)

Just found this forum thread, seems the problem is with the HTML package which I'm extending: https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/25

Let's leave this issue open and see what happens in the next couple weeks, I'd like to avoid trying to debug and fix it in this package if there's an upstream fix.
